server:
  host: "0.0.0.0"
  port: 8080
  tls:
    enabled: false

logging:
  level: "info"

metrics:
  enabled: true
  port: 9090

networkFunction:
  type: "UPF"
  instanceID: "upf-001"
  instanceName: "UPF Packet Handler"
  capacity: 100
  priority: 1
  locality: "local"

nrf:
  url: "http://nrf:8080"
  registrationRetry: 5
  heartbeatInterval: 30

upf:
  dataNetworks:
    - name: "internet"
      pools:
        - cidr: "10.60.0.0/16"
    - name: "ims"
      pools:
        - cidr: "10.61.0.0/16"
  interfaces:
    - name: "n3"
      endpoints: ["0.0.0.0:2152"]
    - name: "n4"
      endpoints: ["0.0.0.0:8805"]
  qosProfiles:
    - id: 1
      guaranteedBitrate: 1000000  # 1 Mbps
      maximumBitrate: 10000000    # 10 Mbps